"""Assemble Korean explanations from the score breakdown.

Every string is a filled template. Nothing here is generated by a model, so an
explanation can never claim something the numbers do not support.
"""

from __future__ import annotations

from app.engine import constants as C
from app.engine.gap import SkillAssessment
from app.engine.models import NormalizedProfile, RoleDef, RoleScore

FACTOR_LABELS_KO = {
    "similarity": "보유 스킬과의 유사도",
    "experience_fit": "경력 연차 적합도",
    "transition": "직무 전환 인접성",
    "industry": "산업 경험 연관성",
}

FACTOR_WEIGHTS = {
    "similarity": C.W_SIMILARITY,
    "experience_fit": C.W_EXPERIENCE,
    "transition": C.W_TRANSITION,
    "industry": C.W_INDUSTRY,
}


def weighted_contributions(score: RoleScore) -> dict[str, float]:
    """Each factor's share of the final score. Sums to `score.final`."""
    values = {
        "similarity": score.similarity,
        "experience_fit": score.experience_fit,
        "transition": score.transition,
        "industry": score.industry,
    }
    return {name: FACTOR_WEIGHTS[name] * value for name, value in values.items()}


def build_explanation(
    score: RoleScore,
    role: RoleDef,
    profile: NormalizedProfile,
    matched: list[SkillAssessment],
    gaps: list[SkillAssessment],
    readiness: float,
) -> tuple[str, list[str]]:
    """Return (headline sentence, supporting bullets), all Korean."""
    contributions = weighted_contributions(score)
    ranked = sorted(contributions.items(), key=lambda item: -item[1])
    top_factors = ", ".join(FACTOR_LABELS_KO[name] for name, _ in ranked[:2])

    headline = (
        f"{role.title_ko} 직무는 {top_factors} 측면에서 지원자님의 경력과 잘 맞습니다. "
        f"필요 역량의 약 {round(readiness * 100)}%를 이미 보유하고 있습니다."
    )

    bullets: list[str] = []
    if matched:
        names = ", ".join(a.skill for a in matched[:3])
        bullets.append(f"이미 보유한 핵심 역량: {names}")
    else:
        bullets.append("이 직무의 필수 역량 중 직접 일치하는 항목이 없습니다.")

    if gaps:
        names = ", ".join(a.skill for a in gaps[:3])
        bullets.append(f"우선 보완할 역량: {names}")
    else:
        bullets.append("이 직무가 요구하는 역량을 모두 충족합니다.")

    partial = [a for a in gaps if a.evidence_skill]
    if partial:
        item = partial[0]
        bullets.append(
            f"보유한 '{item.evidence_skill}' 경험으로 '{item.skill}'을(를) 일부 대체할 수 있습니다."
        )

    bullets.append(
        f"환산 경력 {profile.effective_years:.1f}년 기준으로 "
        f"{role.seniority} 레벨 적합도는 {round(score.experience_fit * 100)}%입니다."
    )
    return headline, bullets
